### ISSUE TITLE
oak-run: Statistics

### ISSUE THREAD

**Issue by asg017** [asg017/oak#44]
From #43, `.oak/oakfile<hash>/runs/<hash>/stats.json` will container statistics about an `oak run` operation on an Oakfile. What statistics could be recorded?

## Time
- [ ] When tasks are `pending`, `resolved`, `rejected`
- [ ] How long tasks take (from above)
- [ ] When a task process starts, ends

## Resource Usage
- [ ] CPU/Memory of `oak run` in general?
- [ ] CPU/Memory of specific tasks? (may not be possible)

## Task Targets
- [ ] Size of generated targets (in bytes)
- [ ] sha checksum of targets ?
